using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Msm.Portfolio.Web.Data;
using Msm.Portfolio.Web.Domain.Entities;

namespace Msm.Portfolio.Web.Services;

/// <summary>What came of giving a model a way in.</summary>
public record ClientAccess(bool Succeeded, string? Email = null, string? Password = null, string? Error = null);

/// <summary>
/// Gives a model the means to sign in to their own dashboard.
/// </summary>
/// <remarks>
/// Onboarding creates the account without a password, because the specification puts
/// account access after purchase. Nothing was ever built to grant it, which left every
/// model with an account they could not reach — including the dashboard their enquiries
/// now arrive on.
///
/// This is the plain version of that: a password generated by MSM and handed over. It is
/// shown once and stored only as a hash, so it cannot be read back off any screen
/// afterwards, and the model can change it themselves once they are in.
/// </remarks>
public interface IClientAccessService
{
    /// <summary>True when this model already has a password, so the wording can say
    /// "reset" rather than "create".</summary>
    Task<bool> HasSignInDetailsAsync(Guid clientId, CancellationToken cancellationToken = default);

    Task<ClientAccess> IssueSignInDetailsAsync(
        Guid clientId, Guid? actingUserId, CancellationToken cancellationToken = default);
}

public class ClientAccessService(
    ApplicationDbContext db,
    UserManager<ApplicationUser> userManager,
    IAuditService audit,
    ILogger<ClientAccessService> logger) : IClientAccessService
{
    public async Task<bool> HasSignInDetailsAsync(
        Guid clientId, CancellationToken cancellationToken = default)
    {
        var user = await FindUserAsync(clientId, cancellationToken);

        return user is not null && await userManager.HasPasswordAsync(user);
    }

    public async Task<ClientAccess> IssueSignInDetailsAsync(
        Guid clientId, Guid? actingUserId, CancellationToken cancellationToken = default)
    {
        var user = await FindUserAsync(clientId, cancellationToken);

        if (user is null)
        {
            return new ClientAccess(false, Error: "That model's account could not be found.");
        }

        var password = PasswordGenerator.Create();

        // Removed and re-added rather than reset with a token: a client account created
        // without a password has no password to reset, and ResetPasswordAsync on one
        // fails rather than setting the first one.
        if (await userManager.HasPasswordAsync(user))
        {
            var removed = await userManager.RemovePasswordAsync(user);

            if (!removed.Succeeded)
            {
                return new ClientAccess(false, Error: Describe(removed));
            }
        }

        var added = await userManager.AddPasswordAsync(user, password);

        if (!added.Succeeded)
        {
            logger.LogWarning(
                "Could not issue sign-in details for client {ClientId}: {Errors}",
                clientId, Describe(added));

            return new ClientAccess(false, Error: Describe(added));
        }

        // The password itself is never recorded — only that access was granted, by whom,
        // and to which account. An audit trail holding passwords would be a list of live
        // credentials for every model on the system.
        audit.Record(nameof(ClientProfile), clientId.ToString(), AuditActions.ClientAccessIssued,
            userId: actingUserId, newValue: user.Email);

        await db.SaveChangesAsync(cancellationToken);

        return new ClientAccess(true, user.Email, password);
    }

    private Task<ApplicationUser?> FindUserAsync(Guid clientId, CancellationToken cancellationToken) =>
        db.ClientProfiles
            .Where(c => c.Id == clientId)
            .Select(c => c.ApplicationUser)
            .FirstOrDefaultAsync(cancellationToken)!;

    private static string Describe(IdentityResult result) =>
        string.Join("; ", result.Errors.Select(e => e.Description));
}
